import sqlite3

def init_db():
    conn = sqlite3.connect(':memory:')
    c = conn.cursor()
    c.execute("CREATE TABLE users (username text, password text)")
    c.execute("INSERT INTO users VALUES ('admin', 'supersecret')")
    conn.commit()
    return conn

def ai_generated_login(conn, username, password):
    """
    This code was generated by an LLM. It "works", but introduces a critical SQL Injection flaw.
    """
    c = conn.cursor()
    
    # --- CRITICAL VULNERABILITY ---
    # The AI used Python f-strings directly inside a SQL query. 
    query = f"SELECT * FROM users WHERE username = '{username}' AND password = '{password}'"
    print(f"Executing: {query}")
    
    c.execute(query)
    user = c.fetchone()
    
    if user:
        return True
    return False

# --- Exploit Simulation ---
if __name__ == "__main__":
    db = init_db()
    
    # 1. Normal Login (Fails)
    print("Normal Attempt:", ai_generated_login(db, "admin", "wrongpassword"))
    
    # 2. The SQL Injection (Succeeds!)
    print("\nHACKER ATTEMPT:")
    hacker_username = "admin' --"
    # The resulting SQL query is: SELECT * FROM users WHERE username = 'admin' --' AND password = '...'
    # The -- comments out the password requirement entirely!
    print("Hacker Status:", ai_generated_login(db, hacker_username, "anything"))
