# The IP address of our Docker container running on our host machine
spring.cassandra.contact-points=127.0.0.1
# The default port for CQL Native Transport
spring.cassandra.port=9042

# The name of the Keyspace we created on Monday. 
# Spring expects this keyspace to ALREADY EXIST. It will not create Keyspaces.
spring.cassandra.keyspace-name=store

# The local data center name defaults to datacenter1 in Docker
spring.cassandra.local-datacenter=datacenter1

# VERY IMPORTANT FOR DEV: 
# This tells Spring Data to automatically scan for @Table POJOs 
# and execute DDL CREATE TABLE statements for us on startup!
spring.data.cassandra.schema-action=create-if-not-exists
