graph TD
    Start((Incoming Call)) --> WelcomePrompt["Play: Thank you for calling Global Airlines."]
    
    WelcomePrompt --> MainMenu{"Input:<br>1 for Flight Status<br>2 for New Flight<br>0 for Agent"}
    
    -- TODO: Continue the Main Menu logic based on the constraints in the README.
    -- Remember to handle "Invalid" inputs by looping back to the MainMenu!
    
    
    
    -- Finish the diagram here
